server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ep-bold-haze-ahghudko-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_9newrc8bExqS
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: yashpithwa786@gmail.com
    password: mwooatxyahtrscijk
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: this-is-a-super-secure-jwt-secret-key-1234567890123456
  expiration: 86400000

# ðŸ”¥ GROQ AI CONFIG
groq:
  api-key: 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
  model: llama-3.1-8b-instant


logging:
  level:
    org.springframework.mail: DEBUG
    jakarta.mail: DEBUG
